### ISSUE TITLE
The submission server is down

### ISSUE THREAD

**Issue by SeanLee97** [princeton-nlp/c-sts#3]
When I submitted test results, the server returned "{"message": "Internal server error"}"

**Comment by closji** [comment]
Hi @SeanLee97,


The server seems to be running okay for me.
Are you using the most recent version of `make_test_submission.py`? It has been updated a bit recently.

The script should be called with the basic format:
```bash
python make_test_submission.py email@gmail.com your-file.json --name experiment-name
```

If you're still having problems, to help debug, would you mind running and reporting the following `jq` commands?

`jq 'keys | length' your-file.json`

`jq 'type' your-file.json`

`jq 'to_entries | .[:3] | from_entries' your-file.json`

These are just to diagnose that the predictions format is as expected.

**Comment by SeanLee97** [comment]
Hi @carlosejimenez , I tried it again, but the error still exists.

I followed your instructions. Below are the outputs of jq commands.
```bash
(py310) $ jq 'keys | length' test_prediction.json
4732
(py310) $ jq 'type' test_prediction.json
"object"
(py310) $ jq 'to_entries | .[:3] | from_entries' test_prediction.json
{
  "0": 0.9671042561531067,
  "1": 0.946521520614624,
  "2": 0.9220250844955444
}
```

**Comment by SeanLee97** [comment]
@carlosejimenez  I have re-run my test and successfully resubmitted the results. The issue seems to have been related to the computation of the Spearman or Pearson scores. I guess there might have been instances where NaN values or other incompatible values were encountered, resulting in a 502 error. Below is my Request ID. If you want to fix this issue, you can trace the ID.

```
{'Date': 'Mon, 23 Oct 2023 12:06:40 GMT', 'Content-Type': 'application/json', 'Content-Length': '36', 'Connection': 'ke
ep-alive', 'x-amzn-RequestId': 'cc1f98cf-ce4a-4654-ba56-362b4c03daa9', 'x-amzn-ErrorType': 'InternalServerErrorException',
'x-amz-apigw-id': 'NQQ4rE-UiYcFQHw='}
```

**Comment by closji** [comment]
Ah, okay, thanks for bringing this up!
